name: Spring Boot MySQL CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Wait for MySQL
      run: |
        for i in `seq 1 30`; do
          nc -zv localhost 3306 && echo Success && exit 0
          echo "Waiting for MySQL..."
          sleep 2
        done
        echo "MySQL did not start in time" && exit 1

    - name: Run tests
      run: mvn clean test

