name: example4
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  flutter_cube: ^0.1.1
  adaptive_bottom_navigation: ^1.0.7
  persistent_bottom_nav_bar: ^6.2.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  video_player: ^2.9.1
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  firebase_core: ^2.3.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.1.0
  kakao_flutter_sdk: ^0.8.0 

dev_dependencies:
   
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/person/
    - assets/person/jindan_normal.jpg
    - assets/person/jindan_Stomach.mp4
    - assets/person/jindan_armsick1.jpg
    - assets/person/jindan_armsick3.jpg
    - assets/person/jindan_armsick5.jpg
    - assets/person/jindan_armsick7.jpg
    - assets/person/jindan_armsick9.jpg
