name: gungangazi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  flutter_cube: ^0.1.1
  adaptive_bottom_navigation: ^1.0.7
  persistent_bottom_nav_bar: ^6.2.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  video_player: ^2.9.1
  fl_chart: ^0.69.0
  easy_sidemenu: ^0.6.0
  dio: ^5.7.0

  cupertino_icons: ^1.0.5
  provider: ^6.0.0
  url_launcher: ^6.0.0
  

  intl: ^0.18.0

dev_dependencies:
   
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0
  build_web_compilers: ^4.0.4
  build_runner: ^2.4.0


flutter:


  uses-material-design: true


  assets:
    - assets/person/
    - assets/person/jindan_normal.jpg
    - assets/person/jindan_armsick1.jpg
    - assets/person/jindan_armsick3.jpg
    - assets/person/jindan_armsick5.jpg
    - assets/person/jindan_armsick7.jpg
    - assets/person/jindan_armsick9.jpg



 
