spring.datasource.url=jdbc:mysql://database-1.c76iaa8ycok0.ap-northeast-2.rds.amazonaws.com:3306/appdb
spring.datasource.username=gungangazi
spring.datasource.password=endbackend!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database=mysql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.address=0.0.0.0
server.tomcat.threads.max=200   
server.tomcat.threads.min-spare=10

debug=true

jwt.secret=jonnajollimandiwannahangoutwithsomeonebuticantthatsreallysadsibaljonnaunjekkazissum
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=gunganghazi@gmail.com
spring.mail.password=aaxy slui ilwq qtmq
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.starttls.enable=false


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.client.registration.google.client-id=423735826070-9dq9dd52a4t5u66krjlg2nm0cpq8f92o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
google.client.android.client-id=423735826070-iml5j92c26kqd9l998683q91hs1slk94.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.redirect-uri=https://gungangazi.site/
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/user.gender.read

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


spring.security.headers.content-security-policy=script-src 'self' 'unsafe-inline' https://accounts.google.com https://www.gstatic.com https://apis.google.com http://people.googleapis.com
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG


