name: CI/CD Pipeline

on: 
  push:
    branches:
      - successful-build
  pull_request:
    branches:
      - successful-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          export PATH="$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter doctor

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Install dependencies
        run: |
          export PATH="$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter pub get --verbose

      - name: Build Flutter web app
        run: |
          export PATH="$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter build web --release

      - name: Build and Test Spring demo
        run: ./mvnw clean install

  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          echo "ec2-13-124-3-87.ap-northeast-2.compute.amazonaws.com" >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./build/web/* ubuntu@ec2-13-124-3-87.ap-northeast-2.compute.amazonaws.com:/var/www/html/

      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-124-3-87.ap-northeast-2.compute.amazonaws.com << 'EOF'
            sudo systemctl restart nginx
          EOF
