name: CI/CD Pipeline

on: 
  push:
    branches:
      - cleanup-branch
  pull_request:
    branches:
      - cleanup-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties
      - uses: actions/upload-artifact@v4
        with:
          name: application.properties
          path: ./src/main/resources/application.properties

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up environment
        run: |
          echo 'export PATH="$PATH:$HOME/flutter/bin"' >> $GITHUB_ENV
      - run: flutter pub get
      - run: flutter build web 

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build and Test Spring demo
        run: ./mvnw clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > GUNGANGAZI.pem
          chmod 600 GUNGANGAZI.pem

          # Flutter 웹 빌드 파일 배포
          scp -o StrictHostKeyChecking=no -i GUNGANGAZI.pem -r ./build/web/* ubuntu@ec2-15-164-140-55.ap-northeast-2.compute.amazonaws.com:/var/www/html/

          # Spring Boot JAR 파일 배포
          scp -o StrictHostKeyChecking=no -i GUNGANGAZI.pem ./target/demo-0.0.1-SNAPSHOT.jar ubuntu@ec2-15-164-140-55.ap-northeast-2.compute.amazonaws.com:/var/app/demo.jar

          # 원격 서버에서 Nginx 재시작 및 Spring Boot 실행
          ssh -o StrictHostKeyChecking=no -i GUNGANGAZI.pem ubuntu@ec2-15-164-140-55.ap-northeast-2.compute.amazonaws.com << EOF
            sudo systemctl restart nginx
            nohup java -jar /var/app/demo.jar &
          EOF

      - name: Cleanup
        run: rm -f GUNGANGAZI.pem
