name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'

      - name: Clear Flutter cache
        run: flutter pub cache repair

      - name: Install Flutter dependencies
        run: flutter pub get --verbose  # verbose 추가

      - name: Build and Test Spring demo
        run: |
          ./mvnw clean install

      - name: Install and Build Dart Frontend
        run: | 
          flutter pub get
          flutter build

      - name: Run Dart Tests
        run: |
          cd frontend
          flutter test

