name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.0.0'
      - run: dart --version

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

     # Flutter SDK 직접 설치
      - name: Install Flutter SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor

    # Dart SDK 설치
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

    # Flutter 패키지 설치
      - name: Install dependencies
        run: flutter pub get

    # 테스트 실행
      - name: Run tests
        run: flutter test
      
          

      - name: Verify Flutter and Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Install Flutter dependencies
        run: flutter pub get --verbose  # verbose 추가

      - name: Build and Test Spring demo
        run: |
          ./mvnw clean install

      - name: Install and Build Dart Frontend
        run: | 
          flutter pub get
          flutter build

      - name: Run Dart Tests
        run: |
          flutter test

