name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # v3으로 업데이트

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Java 17을 사용, 버전 확인 필요
          distribution: 'temurin'

      - name: Set permissions for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build and Test Spring demo
        run: |
          ./mvnw clean install  # Maven을 사용하여 빌드 및 테스트
          
      - name: Checkout repository
        uses: actions/checkout@v3  # v3으로 업데이트

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install and Build Dart Frontend
        run: |
          cd frontend  # 프론트엔드 경로로 이동
          dart pub get  # 의존성 설치
          dart build  # 빌드
          
      - name: Run Dart Tests
        run: |
          cd frontend  # 프론트엔드 경로로 이동
          dart test  # 테스트 실행
