name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Flutter 및 Dart SDK 설치 및 RDS 연결
      - name: Install Flutter, Dart SDKs and Connect to RDS
        run: |
          # Flutter 및 Dart 설치
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils apt-transport-https
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          export PATH="$PATH:$PWD/flutter/bin"
          flutter doctor

          # RDS 연결을 위한 MySQL 클라이언트 설치 및 명령 실행
          sudo apt-get install -y mysql-client
          mysql -h <RDS 엔드포인트> -P 3306 -u <Master username> -p<Master password> -e "SHOW DATABASES;"

      # Flutter 패키지 설치
      - name: Install dependencies
        run: flutter pub get --verbose


    
        run: |
          mysql -h 127.0.0.1 -u root -pendbackend! -e "SHOW DATABASES;"
