name: Build Flutter Web

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          flutter doctor

      - name: Print current working directory  # 현재 작업 디렉토리 확인
        run: pwd

      - name: List current directory contents  # 현재 디렉토리 파일 목록 확인
        run: ls -al

      - name: Clean Flutter project  # 빌드 캐시 정리
        run: flutter clean

      - name: Install dependencies  # 의존성 설치
        run: flutter pub get --verbose

      # Flutter 웹 앱 빌드
      - name: Build Flutter web app
        working-directory: ${{ github.workspace }}
        run: flutter build web --release

      # 빌드 파일 확인
      - name: List build/web directory contents
        run: ls -al build/web
