name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Flutter SDK 설치 및 경로 설정
      - name: Install Flutter SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          echo "FLUTTER_HOME=$(pwd)/flutter" >> $GITHUB_ENV
          echo "$FLUTTER_HOME/bin" >> $GITHUB_PATH
          flutter doctor

      # Flutter 패키지 설치
      - name: Install dependencies
        run: flutter pub get --verbose

      # Spring Build and Test
      - name: Build and Test Spring demo
        run: ./mvnw clean install

      # 테스트 실행
      - name: Run tests
        run: flutter test

      - name: Run tests
        run: flutter test

