name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Flutter 및 Dart SDK 설치
      - name: Install Flutter and Dart SDKs
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip xz-utils apt-transport-https
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
          tar xf flutter_linux_3.24.0-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          echo "$PWD/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          export PATH="$PATH:$PWD/flutter/bin"
          flutter doctor

      # Flutter 패키지 설치
      - name: Install dependencies
        run: flutter pub get --verbose
