name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.0.0'
      - run: dart --version

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'


      
          

      - name: Verify Flutter and Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Install Flutter dependencies
        run: flutter pub get --verbose  # verbose 추가

      - name: Build and Test Spring demo
        run: |
          ./mvnw clean install

      - name: Install and Build Dart Frontend
        run: | 
          flutter pub get
          flutter build

      - name: Run Dart Tests
        run: |
          flutter test

